apiVersion: v1
kind: Service
metadata:
  name: graphrag-api-service
  namespace: graphrag
  labels:
    app: graphrag-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8001
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: graphrag-api
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600

---
apiVersion: v1
kind: Service
metadata:
  name: graphrag-api-nodeport
  namespace: graphrag
  labels:
    app: graphrag-api
spec:
  type: NodePort
  ports:
  - port: 8001
    targetPort: 8001
    nodePort: 30001
    protocol: TCP
    name: http
  selector:
    app: graphrag-api

---
apiVersion: v1
kind: Service
metadata:
  name: graphrag-api-headless
  namespace: graphrag
  labels:
    app: graphrag-api
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    app: graphrag-api