llm:
  api_type: ollama
  model: gemma3:4b
  api_base: http://localhost:11434
  api_version: null
  max_tokens: 4000
  temperature: 0.1
  top_p: 1.0
  request_timeout: 180.0
  max_retries: 3
embeddings:
  api_type: ollama
  model: nomic-embed-text
  api_base: http://localhost:11434
chunks:
  size: 1500
  overlap: 100
  group_by_columns:
  - id
  strategy:
    type: sentence
input:
  type: file
  file_type: text
  base_dir: C:\Users\pierre\AppData\Local\Temp\tmpprcj5o0w
  file_encoding: utf-8
  file_pattern: .*\.txt$
cache:
  type: file
  base_dir: workspaces\test-update-921b4727\output\cache
storage:
  type: file
  base_dir: workspaces\test-update-921b4727\output
entity_extraction:
  strategy:
    type: graph_intelligence
    extraction_prompt: null
    max_gleanings: 1
    entity_types:
    - person
    - organization
    - location
    - event
    - concept
    tuple_delimiter: <|>
    record_delimiter: '##'
    completion_delimiter: <|COMPLETE|>
    encoding_model: cl100k_base
summarize_descriptions:
  strategy:
    type: graph_intelligence
    prompt: null
    max_length: 500
community_reports:
  strategy:
    type: graph_intelligence
    prompt: null
    max_length: 2000
    max_input_length: 8000
claim_extraction:
  strategy:
    type: graph_intelligence
    extraction_prompt: null
    max_gleanings: 1
    tuple_delimiter: <|>
    record_delimiter: '##'
    completion_delimiter: <|COMPLETE|>
    encoding_model: cl100k_base
cluster_graph:
  strategy:
    type: leiden
    max_cluster_size: 10
    use_lcc: true
    seed: 3735928559
    levels:
    - 0
    - 1
    - 2
    - 3
umap:
  enabled: true
  n_neighbors: 15
  n_components: 2
  metric: cosine
  min_dist: 0.1
  spread: 1.0
  random_state: 42
snapshots:
  graphml: true
  raw_entities: true
  top_level_nodes: true
reporting:
  type: file
  base_dir: workspaces\test-update-921b4727\output\reports
