name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
    tags:
      - 'v*'  # Trigger on version tags
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write  # Required for publishing to GitHub Container Registry

env:
  PYTHON_VERSION: '3.12'
  POETRY_VERSION: '1.8.5'

jobs:
  # Basic Code Quality Checks
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run Black
        run: poetry run black --check src/ tests/
        continue-on-error: true  # Don't fail on formatting issues

      - name: Run Ruff
        run: poetry run ruff check src/ tests/
        continue-on-error: true  # Don't fail on linting issues

  # Basic Tests
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: quality
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run basic unit tests
        env:
          # Test environment variables
          DEBUG: "true"
          JWT_SECRET_KEY: "test-secret-key-for-github-actions-ci-cd-pipeline-minimum-32-chars"
          GRAPHRAG_LLM_PROVIDER: "ollama"
          OLLAMA_BASE_URL: "http://localhost:11434"
          OLLAMA_LLM_MODEL: "llama2"
          OLLAMA_EMBEDDING_MODEL: "nomic-embed-text"
        run: poetry run pytest tests/unit/test_config.py -v
        continue-on-error: true  # Don't fail on test issues

  # Build Docker image for development (main branch)
  docker-dev:
    name: Build Development Docker Image
    runs-on: ubuntu-latest
    needs: [quality, test]
    # Only build on main branch pushes (not PRs, not tags)
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push development image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:main
            ghcr.io/${{ github.repository }}:dev-${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.title=GraphRAG API (Development)
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

  # Build Docker image for releases (version tags)
  docker-release:
    name: Build Release Docker Image
    runs-on: ubuntu-latest
    needs: [quality, test]
    # Only build on version tags (v1.0.0, v2.1.3, etc.)
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION_NUMBER=${VERSION#v}" >> $GITHUB_OUTPUT
          # Extract major, minor, patch for additional tags
          if [[ $VERSION =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            echo "MAJOR=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
            echo "MINOR=${BASH_REMATCH[1]}.${BASH_REMATCH[2]}" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push release image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.version.outputs.VERSION }}
            ghcr.io/${{ github.repository }}:${{ steps.version.outputs.VERSION_NUMBER }}
            ghcr.io/${{ github.repository }}:${{ steps.version.outputs.MAJOR }}
            ghcr.io/${{ github.repository }}:${{ steps.version.outputs.MINOR }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.version=${{ steps.version.outputs.VERSION_NUMBER }}
            org.opencontainers.image.title=GraphRAG API
            org.opencontainers.image.description=Production-ready GraphRAG API Service
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ steps.version.outputs.VERSION_NUMBER }}
